In [1]:
# check the predictions and how mlflow does this
# pull these out, or generate them
# go to the scoring for defenders and work out what you can do here + what data you need
#https://www.premierleague.com/en/news/2174909/fpl-basics-scoring
# Features

Features to use:
- ~~predicted minutes~~
- goal record (player or team level?)
- assist record (player or team level?)
- clean sheets (player + team level?)
- defensive contributions (player + team level - also what does this mean?) [link]([company/ymiqeug7uo99i6fj8aom/asset-search-etl](https://www.premierleague.com/en/news/4361991/whats-new-in-202526-fantasy-defensive-contributions))
- disciplinary record (player + team)
- goals conceded (team level)
- home vs away 
- opposition strength

In [2]:
import duckdb
import polars as pl
from matplotlib import pyplot as plt

from fantasy_football.constants import DATA_FOLDER

In [3]:
DATABASE_PATH = DATA_FOLDER / "fantasy_football.duckdb"
connection = duckdb.connect(DATABASE_PATH)

In [15]:
res = connection.sql("SELECT * FROM player_week").pl()
res.head(10)

shape: (10, 11)
┌─────────┬─────┬─────────┬───────────────────┬───┬─────────┬───────┬──────────────┬───────┐
│ season  ┆ gw  ┆ element ┆ name              ┆ … ┆ minutes ┆ round ┆ total_points ┆ value │
│ ---     ┆ --- ┆ ---     ┆ ---               ┆   ┆ ---     ┆ ---   ┆ ---          ┆ ---   │
│ str     ┆ i64 ┆ i64     ┆ str               ┆   ┆ i64     ┆ i64   ┆ i64          ┆ i64   │
╞═════════╪═════╪═════════╪═══════════════════╪═══╪═════════╪═══════╪══════════════╪═══════╡
│ 2024-25 ┆ 10  ┆ 488     ┆ Fraser Forster    ┆ … ┆ 0       ┆ 10    ┆ 0            ┆ 44    │
│ 2024-25 ┆ 18  ┆ 651     ┆ Orel Mangala      ┆ … ┆ 90      ┆ 18    ┆ 1            ┆ 50    │
│ 2024-25 ┆ 34  ┆ 499     ┆ Pape Matar Sarr   ┆ … ┆ 45      ┆ 34    ┆ 1            ┆ 47    │
│ 2024-25 ┆ 3   ┆ 411     ┆ Lewis Miley       ┆ … ┆ 0       ┆ 3     ┆ 0            ┆ 50    │
│ 2024-25 ┆ 6   ┆ 247     ┆ Alex Iwobi        ┆ … ┆ 90      ┆ 6     ┆ 3            ┆ 55    │
│ 2024-25 ┆ 4   ┆ 285     ┆ Boubakary Soumaré ┆ … ┆ 0       ┆ 4     ┆ 0            ┆ 45    │
│ 2024-25 ┆ 18  ┆ 342     ┆ Bernardo Veiga de ┆ … ┆ 90      ┆ 18    ┆ 9            ┆ 63    │
│         ┆     ┆         ┆ Carvalho e S…     ┆   ┆         ┆       ┆              ┆       │
│ 2024-25 ┆ 4   ┆ 469     ┆ Alex McCarthy     ┆ … ┆ 0       ┆ 4     ┆ 0            ┆ 45    │
│ 2024-25 ┆ 14  ┆ 142     ┆ Jason Steele      ┆ … ┆ 0       ┆ 14    ┆ 0            ┆ 42    │
│ 2024-25 ┆ 17  ┆ 442     ┆ Ibrahim Sangaré   ┆ … ┆ 0       ┆ 17    ┆ 0            ┆ 44    │
└─────────┴─────┴─────────┴───────────────────┴───┴─────────┴───────┴──────────────┴───────┘

In [ ]:
match = connection.sql("SELECT * FROM player_match").pl()
match.head(10)

shape: (10, 8)
┌─────────┬─────┬─────────┬──────────┬─────────┬─────────┬──────────────┬─────────────────────┐
│ season  ┆ gw  ┆ element ┆ opponent ┆ is_home ┆ minutes ┆ total_points ┆ kickoff_time        │
│ ---     ┆ --- ┆ ---     ┆ ---      ┆ ---     ┆ ---     ┆ ---          ┆ ---                 │
│ str     ┆ i64 ┆ i64     ┆ i64      ┆ bool    ┆ i64     ┆ i64          ┆ datetime[μs]        │
╞═════════╪═════╪═════════╪══════════╪═════════╪═════════╪══════════════╪═════════════════════╡
│ 2024-25 ┆ 1   ┆ 77      ┆ 16       ┆ false   ┆ 62      ┆ 2            ┆ 2024-08-17 14:00:00 │
│ 2024-25 ┆ 1   ┆ 427     ┆ 3        ┆ true    ┆ 0       ┆ 0            ┆ 2024-08-17 14:00:00 │
│ 2024-25 ┆ 1   ┆ 22      ┆ 20       ┆ true    ┆ 0       ┆ 0            ┆ 2024-08-17 14:00:00 │
│ 2024-25 ┆ 1   ┆ 197     ┆ 4        ┆ false   ┆ 0       ┆ 0            ┆ 2024-08-18 13:00:00 │
│ 2024-25 ┆ 1   ┆ 584     ┆ 15       ┆ false   ┆ 70      ┆ 1            ┆ 2024-08-17 14:00:00 │
│ 2024-25 ┆ 1   ┆ 52      ┆ 19       ┆ false   ┆ 90      ┆ 2            ┆ 2024-08-17 16:30:00 │
│ 2024-25 ┆ 1   ┆ 215     ┆ 4        ┆ false   ┆ 0       ┆ 0            ┆ 2024-08-18 13:00:00 │
│ 2024-25 ┆ 1   ┆ 609     ┆ 11       ┆ false   ┆ 0       ┆ 0            ┆ 2024-08-19 19:00:00 │
│ 2024-25 ┆ 1   ┆ 550     ┆ 1        ┆ false   ┆ 90      ┆ 2            ┆ 2024-08-17 14:00:00 │
│ 2024-25 ┆ 1   ┆ 610     ┆ 11       ┆ false   ┆ 0       ┆ 0            ┆ 2024-08-19 19:00:00 │
└─────────┴─────┴─────────┴──────────┴─────────┴─────────┴──────────────┴─────────────────────┘

In [ ]:
minutes_prediction = connection.sql("SELECT * FROM minutes_prediction").pl()
minutes_prediction.head(10)

shape: (10, 11)
┌─────────┬─────┬─────────┬──────────┬───┬──────────────┬──────────────┬─────────────┬─────────────┐
│ season  ┆ gw  ┆ element ┆ opponent ┆ … ┆ expected_min ┆ model_versio ┆ prediction_ ┆ snapshot_ca │
│ ---     ┆ --- ┆ ---     ┆ ---      ┆   ┆ utes         ┆ n            ┆ kind        ┆ ptured_at   │
│ str     ┆ i64 ┆ i64     ┆ i64      ┆   ┆ ---          ┆ ---          ┆ ---         ┆ ---         │
│         ┆     ┆         ┆          ┆   ┆ f64          ┆ str          ┆ str         ┆ datetime[μs │
│         ┆     ┆         ┆          ┆   ┆              ┆              ┆             ┆ ]           │
╞═════════╪═════╪═════════╪══════════╪═══╪══════════════╪══════════════╪═════════════╪═════════════╡
│ 2016-17 ┆ 1   ┆ 6       ┆ 9        ┆ … ┆ 57.986142    ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 7       ┆ 9        ┆ … ┆ 41.410956    ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 11      ┆ 9        ┆ … ┆ 32.348861    ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 13      ┆ 9        ┆ … ┆ 57.773438    ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 14      ┆ 9        ┆ … ┆ 65.806122    ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 16      ┆ 9        ┆ … ┆ 60.369518    ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 17      ┆ 9        ┆ … ┆ 46.22967     ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 18      ┆ 9        ┆ … ┆ 46.22967     ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 21      ┆ 9        ┆ … ┆ 46.22967     ┆ 7            ┆ backfill    ┆ null        │
│ 2016-17 ┆ 1   ┆ 22      ┆ 9        ┆ … ┆ 34.954693    ┆ 7            ┆ backfill    ┆ null        │
└─────────┴─────┴─────────┴──────────┴───┴──────────────┴──────────────┴─────────────┴─────────────┘

In [20]:
player_season = connection.sql("SELECT DISTINCT season FROM player_season").pl()
player_season.head(10)

shape: (10, 1)
┌─────────┐
│ season  │
│ ---     │
│ str     │
╞═════════╡
│ 2019-20 │
│ 2017-18 │
│ 2024-25 │
│ 2025-26 │
│ 2020-21 │
│ 2018-19 │
│ 2026-27 │
│ 2021-22 │
│ 2016-17 │
│ 2022-23 │
└─────────┘

In [22]:
base_sql = """
SELECT 
    m.season
    ,s.first_name || ' ' || s.second_name as player_name
    ,m.element
    ,m.total_points
    ,m.kickoff_time
    ,m.gw
    ,m.opponent
    ,m.minutes
    ,mn.expected_minutes
    ,mn.p_zero
    ,mn.p_partial
    ,mn.p_sixty_plus

FROM player_match m 

LEFT JOIN player_season s ON m.element = s.element
    AND m.season = s.season
LEFT JOIN minutes_prediction mn ON m.element = mn.element
    AND m.season = mn.season
    AND m.gw = mn.gw
    AND m.element = mn.element
    AND m.opponent = mn.opponent

WHERE m.season = '2025-26'
"""

base = connection.sql(base_sql).pl()
base.head(10)

shape: (10, 12)
┌─────────┬────────────┬─────────┬────────────┬───┬────────────┬──────────┬───────────┬────────────┐
│ season  ┆ player_nam ┆ element ┆ total_poin ┆ … ┆ expected_m ┆ p_zero   ┆ p_partial ┆ p_sixty_pl │
│ ---     ┆ e          ┆ ---     ┆ ts         ┆   ┆ inutes     ┆ ---      ┆ ---       ┆ us         │
│ str     ┆ ---        ┆ i64     ┆ ---        ┆   ┆ ---        ┆ f64      ┆ f64       ┆ ---        │
│         ┆ str        ┆         ┆ i64        ┆   ┆ f64        ┆          ┆           ┆ f64        │
╞═════════╪════════════╪═════════╪════════════╪═══╪════════════╪══════════╪═══════════╪════════════╡
│ 2025-26 ┆ Reinildo   ┆ 541     ┆ 6          ┆ … ┆ 39.220002  ┆ 0.405154 ┆ 0.119855  ┆ 0.474991   │
│         ┆ Mandava    ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Lewis      ┆ 57      ┆ 0          ┆ … ┆ 17.053931  ┆ 0.67393  ┆ 0.164474  ┆ 0.161596   │
│         ┆ Dobbin     ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Ryan       ┆ 87      ┆ 0          ┆ … ┆ 0.701187   ┆ 0.983624 ┆ 0.011711  ┆ 0.004665   │
│         ┆ Christie   ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Zeki       ┆ 216     ┆ 0          ┆ … ┆ 0.220596   ┆ 0.994143 ┆ 0.00486   ┆ 0.000997   │
│         ┆ Amdouni    ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Lucas      ┆ 612     ┆ 2          ┆ … ┆ 55.443915  ┆ 0.125518 ┆ 0.225382  ┆ 0.649099   │
│         ┆ Tolentino  ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│         ┆ Coelho de  ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│         ┆ Lima       ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Jorrel     ┆ 672     ┆ 0          ┆ … ┆ 47.238095  ┆ 0.300674 ┆ 0.115808  ┆ 0.583518   │
│         ┆ Hato       ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Myles Pear ┆ 133     ┆ 0          ┆ … ┆ 18.052887  ┆ 0.64928  ┆ 0.183358  ┆ 0.167362   │
│         ┆ t-Harris   ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Ben Gannon ┆ 391     ┆ 0          ┆ … ┆ 20.54283   ┆ 0.612145 ┆ 0.189918  ┆ 0.197937   │
│         ┆ -Doak      ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Bashir     ┆ 193     ┆ 0          ┆ … ┆ 1.071356   ┆ 0.980764 ┆ 0.008252  ┆ 0.010984   │
│         ┆ Humphreys  ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
│ 2025-26 ┆ Romain     ┆ 92      ┆ 0          ┆ … ┆ 25.243339  ┆ 0.528394 ┆ 0.225047  ┆ 0.246559   │
│         ┆ Faivre     ┆         ┆            ┆   ┆            ┆          ┆           ┆            │
└─────────┴────────────┴─────────┴────────────┴───┴────────────┴──────────┴───────────┴────────────┘