In [1]:
import pandas as pd
import polars as pl
import ScraperFC as sfc

from fantasy_football.constants import PROJECT_ROOT
from fantasy_football.storage.database import get_connection    
from fantasy_football.storage.tables import MINUTES_PREDICTION

In [2]:
tm = sfc.Transfermarkt()
connection = get_connection()

In [3]:
seasons = ["16/17", "17/18", "18/19", "19/20", "20/21", "21/22", "22/23", "23/24", "24/25", "25/26", "26/27"]

In [4]:
def get_player_links(seasons: list[str]) -> list[str]:
    all_player_links = []
    for season in seasons:
        print(f"Getting player links for {season}")
        all_player_links.extend(tm.get_player_links(year=season, league="England Premier League"))
    
    return all_player_links

In [5]:
player_links = get_player_links(seasons)

Getting player links for 16/17
Running

16/17 England Premier League player links: 100%|██████████| 20/20 [00:34<00:00,  1.71s/it]

Getting player links for 17/18

17/18 England Premier League player links: 100%|██████████| 20/20 [00:35<00:00,  1.79s/it]

Getting player links for 18/19

18/19 England Premier League player links: 100%|██████████| 20/20 [00:41<00:00,  2.07s/it]

Getting player links for 19/20

19/20 England Premier League player links: 100%|██████████| 20/20 [00:40<00:00,  2.02s/it]

Getting player links for 20/21

20/21 England Premier League player links: 100%|██████████| 20/20 [00:33<00:00,  1.70s/it]

Getting player links for 21/22

21/22 England Premier League player links: 100%|██████████| 20/20 [00:30<00:00,  1.55s/it]

Getting player links for 22/23

22/23 England Premier League player links: 100%|██████████| 20/20 [01:49<00:00,  5.49s/it]

Getting player links for 23/24

23/24 England Premier League player links: 100%|██████████| 20/20 [00:51<00:00,  2.56s/it]

Getting player links for 24/25

24/25 England Premier League player links: 100%|██████████| 20/20 [01:03<00:00,  3.16s/it]

Getting player links for 25/26

25/26 England Premier League player links: 100%|██████████| 20/20 [00:47<00:00,  2.37s/it]

Getting player links for 26/27

26/27 England Premier League player links: 100%|██████████| 20/20 [00:24<00:00,  1.20s/it]

In [12]:
player_links

['https://www.transfermarkt.us/jonathan-calleri/marktwertverlauf/spieler/284727',
 'https://www.transfermarkt.us/ademola-lookman/profil/spieler/406040',
 'https://www.transfermarkt.us/david-nugent/profil/spieler/33963',
 'https://www.transfermarkt.us/luke-amos/profil/spieler/258912',
 'https://www.transfermarkt.us/matt-phillips/profil/spieler/77274',
 'https://www.transfermarkt.us/christian-fuchs/marktwertverlauf/spieler/6636',
 'https://www.transfermarkt.us/fabio-borini/marktwertverlauf/spieler/96754',
 'https://www.transfermarkt.us/will-buckley/profil/spieler/77329',
 'https://www.transfermarkt.us/lukasz-fabianski/marktwertverlauf/spieler/29692',
 'https://www.transfermarkt.us/daniel-amartey/marktwertverlauf/spieler/214056',
 'https://www.transfermarkt.us/wilfried-zaha/profil/spieler/145988',
 'https://www.transfermarkt.us/joel-robles/profil/spieler/101118',
 'https://www.transfermarkt.us/james-wilson/marktwertverlauf/spieler/214104',
 'https://www.transfermarkt.us/dele-alli/profil/spieler/207929',
 'https://www.transfermarkt.us/santi-cazorla/profil/spieler/15799',
 'https://www.transfermarkt.us/mile-jedinak/profil/spieler/28336',
 'https://www.transfermarkt.us/tom-davies/marktwertverlauf/spieler/314210',
 'https://www.transfermarkt.us/gabriel-paulista/marktwertverlauf/spieler/149498',
 'https://www.transfermarkt.us/leighton-baines/marktwertverlauf/spieler/13507',
 'https://www.transfermarkt.us/emre-can/profil/spieler/119296',
 'https://www.transfermarkt.us/granit-xhaka/profil/spieler/111455',
 'https://www.transfermarkt.us/james-weir/marktwertverlauf/spieler/251058',
 'https://www.transfermarkt.us/connor-roberts/profil/spieler/214666',
 'https://www.transfermarkt.us/steven-defour/marktwertverlauf/spieler/33866',
 'https://www.transfermarkt.us/will-buckley/marktwertverlauf/spieler/77329',
 'https://www.transfermarkt.us/wojciech-szczesny/profil/spieler/44058',
 'https://www.transfermarkt.us/charlie-austin/profil/spieler/129627',
 'https://www.transfermarkt.us/joe-gomez/marktwertverlauf/spieler/256178',
 'https://www.transfermarkt.us/paulo-gazzaniga/marktwertverlauf/spieler/195488',
 'https://www.transfermarkt.us/kevin-wimmer/marktwertverlauf/spieler/122675',
 'https://www.transfermarkt.us/vincent-janssen/profil/spieler/207015',
 'https://www.transfermarkt.us/jack-rose/profil/spieler/186923',
 'https://www.transfermarkt.us/moses-odubajo/profil/spieler/163738',
 'https://www.transfermarkt.us/ramadan-sobhi/profil/spieler/312017',
 'https://www.transfermarkt.us/ben-watson/profil/spieler/14081',
 'https://www.transfermarkt.us/alex-baptiste/marktwertverlauf/spieler/16660',
 'https://www.transfermarkt.us/rickie-lambert/marktwertverlauf/spieler/49655',
 'https://www.transfermarkt.us/laurent-koscielny/marktwertverlauf/spieler/76277',
 'https://www.transfermarkt.us/ben-mee/marktwertverlauf/spieler/74810',
 'https://www.transfermarkt.us/ramiro-funes-mori/profil/spieler/11111',
 'https://www.transfermarkt.us/brian-lenihan/profil/spieler/241916',
 'https://www.transfermarkt.us/ryan-sweeney/marktwertverlauf/spieler/347666',
 'https://www.transfermarkt.us/willian/profil/spieler/52769',
 'https://www.transfermarkt.us/paddy-mcnair/profil/spieler/167268',
 'https://www.transfermarkt.us/paddy-mcnair/marktwertverlauf/spieler/167268',
 'https://www.transfermarkt.us/ben-gibson/marktwertverlauf/spieler/128904',
 'https://www.transfermarkt.us/harry-kane/profil/spieler/132098',
 'https://www.transfermarkt.us/jack-stephens/profil/spieler/163744',
 'https://www.transfermarkt.us/modou-barrow/marktwertverlauf/spieler/189070',
 'https://www.transfermarkt.us/damien-delaney/profil/spieler/36861',
 'https://www.transfermarkt.us/scott-arfield/marktwertverlauf/spieler/55291',
 'https://www.transfermarkt.us/donald-love/profil/spieler/179451',
 'https://www.transfermarkt.us/antonio-barragan/profil/spieler/32522',
 'https://www.transfermarkt.us/george-honeyman/profil/spieler/218140',
 'https://www.transfermarkt.us/nathaniel-clyne/profil/spieler/85177',
 'https://www.transfermarkt.us/jordan-ayew/profil/spieler/108354',
 'https://www.transfermarkt.us/joleon-lescott/profil/spieler/4241',
 'https://www.transfermarkt.us/marten-de-roon/marktwertverlauf/spieler/133179',
 'https://www.transfermarkt.us/nathan-holland/profil/spieler/337321',
 'https://www.transfermarkt.us/adnan-januzaj/profil/spieler/177847',
 'https://www.transfermarkt.us/gaston-ramirez/profil/spieler/123742',
 'https://www.transfermarkt.us/james-mcclean/profil/spieler/85935',
 'https://www.transfermarkt.us/franck-tabanou/profil/spieler/66413',
 'https://www.transfermarkt.us/antonio-valencia/profil/spieler/33544',
 'https://www.transfermarkt.us/emerson-hyndman/profil/spieler/223047',
 'https://www.transfermarkt.us/joel-campbell/profil/spieler/131248',
 'https://www.transfermarkt.us/paul-robinson/marktwertverlauf/spieler/3630',
 'https://www.transfermarkt.us/marcos-alonso/marktwertverlauf/spieler/112515',
 'https://www.transfermarkt.us/charlie-adam/profil/spieler/28990',
 'https://www.transfermarkt.us/manolo-gabbiadini/marktwertverlauf/spieler/112343',
 'https://www.transfermarkt.us/jonathan-benteke/profil/spieler/273773',
 'https://www.transfermarkt.us/james-husband/marktwertverlauf/spieler/167393',
 'https://www.transfermarkt.us/fernando/marktwertverlauf/spieler/51174',
 'https://www.transfermarkt.us/adam-lallana/profil/spieler/43530',
 'https://www.transfermarkt.us/julian-speroni/profil/spieler/12814',
 'https://www.transfermarkt.us/lee-cattermole/profil/spieler/37363',
 'https://www.transfermarkt.us/fraizer-campbell/profil/spieler/42411',
 'https://www.transfermarkt.us/nathan-redmond/marktwertverlauf/spieler/129078',
 'https://www.transfermarkt.us/jordan-rhodes/marktwertverlauf/spieler/48950',
 'https://www.transfermarkt.us/adam-federici/profil/spieler/4233',
 'https://www.transfermarkt.us/modou-barrow/profil/spieler/189070',
 'https://www.transfermarkt.us/cesc-fabregas/marktwertverlauf/spieler/8806',
 'https://www.transfermarkt.us/joel-pereira/profil/spieler/192611',
 'https://www.transfermarkt.us/joel-taylor/profil/spieler/258310',
 'https://www.transfermarkt.us/leroy-sane/marktwertverlauf/spieler/192565',
 'https://www.transfermarkt.us/tom-anderson/profil/spieler/128828',
 'https://www.transfermarkt.us/jordy-clasie/profil/spieler/104223',
 'https://www.transfermarkt.us/ben-hamer/marktwertverlauf/spieler/67283',
 'https://www.transfermarkt.us/aleksandar-kolarov/marktwertverlauf/spieler/46156',
 'https://www.transfermarkt.us/gaston-ramirez/marktwertverlauf/spieler/123742',
 'https://www.transfermarkt.us/steven-davis/marktwertverlauf/spieler/28973',
 'https://www.transfermarkt.us/nacer-chadli/marktwertverlauf/spieler/59631',
 'https://www.transfermarkt.us/abdul-rahman-baba/marktwertverlauf/spieler/224884',
 'https://www.transfermarkt.us/moussa-sissoko/profil/spieler/46001',
 'https://www.transfermarkt.us/charlie-daniels/profil/spieler/61819',
 'https://www.transfermarkt.us/valon-behrami/marktwertverlauf/spieler/21905',
 'https://www.transfermarkt.us/curtis-davies/marktwertverlauf/spieler/18227',
 'https://www.transfermarkt.us/daniel-sturridge/marktwertverlauf/spieler/47082',
 'https://www.transfermarkt.us/artur-boruc/profil/spieler/15220',
 'https://www.transfermarkt.us/maksymilian-stryjek/profil/spieler/240457',
 'https://www.transfermarkt.us/ola-aina/profil/spieler/236490',
 'https://www.transfermarkt.us/mason-holgate/marktwertverlauf/spieler/348623',
 'https://www.transfermarkt.us/sam-gallagher/profil/spieler/227183',
 'https://www.transfermarkt.us/charlie-adam/marktwertverlauf/spieler/28990',
 'https://www.transfermarkt.us/luis-hernandez/marktwertverlauf/spieler/62945',
 'https://www.transfermarkt.us/clinton-njie/marktwertverlauf/spieler/241119',
 'https://www.transfermarkt.us/alberto-moreno/profil/spieler/207917',
 'https://www.transfermarkt.us/marc-muniesa/profil/spieler/74228',
 'https://www.transfermarkt.us/raheem-sterling/profil/spieler/134425',
 'https://www.transfermarkt.us/leon-britton/marktwertverlauf/spieler/40043',
 'https://www.transfermarkt.us/daryl-janmaat/profil/spieler/60744',
 'https://www.transfermarkt.us/luis-hernandez/profil/spieler/62945',
 'https://www.transfermarkt.us/adam-federici/marktwertverlauf/spieler/4233',
 'https://www.transfermarkt.us/joe-gomez/profil/spieler/256178',
 'https://www.transfermarkt.us/sullay-kaikai/profil/spieler/244130',
 'https://www.transfermarkt.us/nacer-chadli/profil/spieler/59631',
 'https://www.transfermarkt.us/bafetimbi-gomis/marktwertverlauf/spieler/22388',
 'https://www.transfermarkt.us/daniel-bachmann/profil/spieler/120186',
 'https://www.transfermarkt.us/bakary-sako/marktwertverlauf/spieler/46791',
 'https://www.transfermarkt.us/jonathan-calleri/profil/spieler/284727',
 'https://www.transfermarkt.us/todd-kane/profil/spieler/154287',
 'https://www.transfermarkt.us/pablo-maffeo/marktwertverlauf/spieler/251876',
 'https://www.transfermarkt.us/ryan-inniss/profil/spieler/183284',
 'https://www.transfermarkt.us/gabriel-jesus/marktwertverlauf/spieler/363205',
 'https://www.transfermarkt.us/kenji-gorre/profil/spieler/374889',
 'https://www.transfermarkt.us/nick-pope/profil/spieler/192080',
 'https://www.transfermarkt.us/gylfi-sigurdsson/profil/spieler/90466',
 'https://www.transfermarkt.us/michael-kightly/profil/spieler/25366',
 'https://www.transfermarkt.us/bacary-sagna/marktwertverlauf/spieler/26764',
 'https://www.transfermarkt.us/marko-grujic/profil/spieler/222813',
 'https://www.transfermarkt.us/kyle-walker-peters/profil/spieler/341051',
 'https://www.transfermarkt.us/ngolo-kante/marktwertverlauf/spieler/225083',
 'https://www.transfermarkt.us/cheikhou-kouyate/profil/spieler/66934',
 'https://www.transfermarkt.us/eric-dier/marktwertverlauf/spieler/175722',
 'https://www.transfermarkt.us/aaron-ramsdale/profil/spieler/427568',
 'https://www.transfermarkt.us/lucas-piazon/profil/spieler/176485',
 'https://www.transfermarkt.us/federico-fazio/marktwertverlauf/spieler/45314',
 'https://www.transfermarkt.us/mohamed-elneny/profil/spieler/160438',
 'https://www.transfermarkt.us/chris-smalling/profil/spieler/103427',
 'https://www.transfermarkt.us/mike-van-der-hoorn/marktwertverlauf/spieler/187105',
 'https://www.transfermarkt.us/connor-ripley/marktwertverlauf/spieler/163531',
 'https://www.transfermarkt.us/matt-miazga/marktwertverlauf/spieler/245893',
 'https://www.transfermarkt.us/etienne-capoue/profil/spieler/63494',
 'https://www.transfermarkt.us/andreas-christensen/marktwertverlauf/spieler/196948',
 'https://www.transfermarkt.us/christian-eriksen/marktwertverlauf/spieler/69633',
 'https://www.transfermarkt.us/jamie-vardy/profil/spieler/197838',
 'https://www.transfermarkt.us/adam-smith/marktwertverlauf/spieler/61841',
 'https://www.transfermarkt.us/aaron-ramsey/marktwertverlauf/spieler/50057',
 'https://www.transfermarkt.us/danny-ings/profil/spieler/134294',
 'https://www.transfermarkt.us/loic-remy/profil/spieler/45121',
 'https://www.transfermarkt.us/lee-grant/marktwertverlauf/spieler/13460',
 'https://www.transfermarkt.us/luciano-narsingh/profil/spieler/72462',
 'https://www.transfermarkt.us/kevin-de-bruyne/profil/spieler/88755',
 'https://www.transfermarkt.us/sam-vokes/marktwertverlauf/spieler/48078',
 'https://www.transfermarkt.us/sam-byram/marktwertverlauf/spieler/236953',
 'https://www.transfermarkt.us/mj-williams/profil/spieler/279454',
 'https://www.transfermarkt.us/virgil-van-dijk/profil/spieler/139208',
 'https://www.transfermarkt.us/jordan-ayew/marktwertverlauf/spieler/108354',
 'https://www.transfermarkt.us/daley-blind/profil/spieler/12282',
 'https://www.transfermarkt.us/oleksandr-zinchenko/marktwertverlauf/spieler/203853',
 'https://www.transfermarkt.us/geoff-cameron/marktwertverlauf/spieler/31642',
 'https://www.transfermarkt.us/nacho-monreal/profil/spieler/43003',
 'https://www.transfermarkt.us/lewis-cook/marktwertverlauf/spieler/249089',
 'https://www.transfermarkt.us/enner-valencia/profil/spieler/139503',
 'https://www.transfermarkt.us/mousa-dembele/marktwertverlauf/spieler/19368',
 'https://www.transfermarkt.us/ashley-barnes/profil/spieler/63200',
 'https://www.transfermarkt.us/danny-lafferty/profil/spieler/85928',
 'https://www.transfermarkt.us/gary-cahill/profil/spieler/27511',
 'https://www.transfermarkt.us/kevin-long/profil/spieler/111114',
 'https://www.transfermarkt.us/elliot-embleton/profil/spieler/364828',
 'https://www.transfermarkt.us/harry-maguire/marktwertverlauf/spieler/177907',
 'https://www.transfermarkt.us/martin-olsson/profil/spieler/38073',
 'https://www.transfermarkt.us/bernardo-espinosa/marktwertverlauf/spieler/64598',
 'https://www.transfermarkt.us/riyad-mahrez/marktwertverlauf/spieler/171424',
 'https://www.transfermarkt.us/santi-cazorla/marktwertverlauf/spieler/15799',
 'https://www.transfermarkt.us/abel-hernandez/marktwertverlauf/spieler/76608',
 'https://www.transfermarkt.us/abdul-rahman-baba/profil/spieler/224884',
 'https://www.transfermarkt.us/jordan-holmes/profil/spieler/399158',
 'https://www.transfermarkt.us/james-milner/profil/spieler/3333',
 'https://www.transfermarkt.us/mario-suarez/marktwertverlauf/spieler/37337',
 'https://www.transfermarkt.us/markus-henriksen/marktwertverlauf/spieler/122011',
 'https://www.transfermarkt.us/eric-bailly/profil/spieler/286384',
 'https://www.transfermarkt.us/robert-snodgrass/marktwertverlauf/spieler/22614',
 'https://www.transfermarkt.us/harvey-rodgers/profil/spieler/459873',
 'https://www.transfermarkt.us/sheyi-ojo/marktwertverlauf/spieler/236510',
 'https://www.transfermarkt.us/nampalys-mendy/marktwertverlauf/spieler/111051',
 'https://www.transfermarkt.us/glen-johnson/marktwertverlauf/spieler/3881',
 'https://www.transfermarkt.us/kristoffer-nordfeldt/marktwertverlauf/spieler/75890',
 'https://www.transfermarkt.us/jack-butland/profil/spieler/128899',
 'https://www.transfermarkt.us/juan-cuadrado/profil/spieler/91970',
 'https://www.transfermarkt.us/jordan-henderson/marktwertverlauf/spieler/61651',
 'https://www.transfermarkt.us/ryan-allsop/profil/spieler/111073',
 'https://www.transfermarkt.us/fabio/marktwertverlauf/spieler/61891',
 'https://www.transfermarkt.us/artur-boruc/marktwertverlauf/spieler/15220',
 'https://www.transfermarkt.us/jesse-lingard/profil/spieler/141660',
 'https://www.transfermarkt.us/josh-tymon/marktwertverlauf/spieler/419929',
 'https://www.transfermarkt.us/evandro/profil/spieler/53359',
 'https://www.transfermarkt.us/wes-morgan/profil/spieler/10003',
 'https://www.transfermarkt.us/matty-willock/profil/spieler/289845',
 'https://www.transfermarkt.us/anton-walkes/profil/spieler/307763',
 'https://www.transfermarkt.us/rudy-gestede/profil/spieler/39908',
 'https://www.transfermarkt.us/james-ward-prowse/profil/spieler/181579',
 'https://www.transfermarkt.us/fernando/profil/spieler/51174',
 'https://www.transfermarkt.us/fabian-delph/profil/spieler/50362',
 'https://www.transfermarkt.us/charlie-rowan/profil/spieler/479944',
 'https://www.transfermarkt.us/georges-kevin-nkoudou/marktwertverlauf/spieler/215679',
 'https://www.transfermarkt.us/michael-carrick/marktwertverlauf/spieler/3878',
 'https://www.transfermarkt.us/alex-mccarthy/profil/spieler/95976',
 'https://www.transfermarkt.us/sam-mcqueen/marktwertverlauf/spieler/226968',
 'https://www.transfermarkt.us/baily-cargill/profil/spieler/293450',
 'https://www.transfermarkt.us/rhoys-wiggins/marktwertverlauf/spieler/42298',
 'https://www.transfermarkt.us/yaya-sanogo/marktwertverlauf/spieler/127194',
 'https://www.transfermarkt.us/oleksandr-zinchenko/profil/spieler/203853',
 'https://www.transfermarkt.us/anthony-martial/profil/spieler/182877',
 'https://www.transfermarkt.us/stephen-kingsley/marktwertverlauf/spieler/184398',
 'https://www.transfermarkt.us/sam-johnstone/marktwertverlauf/spieler/110864',
 'https://www.transfermarkt.us/scott-arfield/profil/spieler/55291',
 'https://www.transfermarkt.us/anton-walkes/marktwertverlauf/spieler/307763',
 'https://www.transfermarkt.us/demarai-gray/marktwertverlauf/spieler/292417',
 'https://www.transfermarkt.us/ander-herrera/profil/spieler/99343',
 'https://www.transfermarkt.us/thibaut-courtois/marktwertverlauf/spieler/108390',
 'https://www.transfermarkt.us/nicolas-otamendi/marktwertverlauf/spieler/54781',
 'https://www.transfermarkt.us/aiden-oneill/marktwertverlauf/spieler/385918',
 'https://www.transfermarkt.us/allan-mcgregor/marktwertverlauf/spieler/9422',
 'https://www.transfermarkt.us/sebastien-pocognoli/marktwertverlauf/spieler/17804',
 'https://www.transfermarkt.us/craig-cathcart/marktwertverlauf/spieler/59606',
 'https://www.transfermarkt.us/paulo-gazzaniga/profil/spieler/195488',
 'https://www.transfermarkt.us/moussa-sissoko/marktwertverlauf/spieler/46001',
 'https://www.transfermarkt.us/joe-allen/profil/spieler/51452',
 'https://www.transfermarkt.us/brahim-diaz/profil/spieler/314678',
 'https://www.transfermarkt.us/angus-gunn/profil/spieler/201574',
 'https://www.transfermarkt.us/callum-mcmanaman/marktwertverlauf/spieler/61711',
 'https://www.transfermarkt.us/harry-wilson/marktwertverlauf/spieler/279455',
 'https://www.transfermarkt.us/matt-grimes/profil/spieler/265471',
 'https://www.transfermarkt.us/manuel-lanzini/marktwertverlauf/spieler/135853',
 'https://www.transfermarkt.us/salomon-rondon/profil/spieler/80197',
 'https://www.transfermarkt.us/craig-cathcart/profil/spieler/59606',
 'https://www.transfermarkt.us/ntumba-massanka/profil/spieler/385922',
 'https://www.transfermarkt.us/shinji-okazaki/marktwertverlauf/spieler/79642',
 'https://www.transfermarkt.us/zlatan-ibrahimovic/profil/spieler/3455',
 'https://www.transfermarkt.us/pablo-maffeo/profil/spieler/251876',
 'https://www.transfermarkt.us/raphael-spiegel/profil/spieler/111428',
 'https://www.transfermarkt.us/ben-davies/profil/spieler/192765',
 'https://www.transfermarkt.us/glenn-whelan/marktwertverlauf/spieler/12124',
 'https://www.transfermarkt.us/stephen-ward/marktwertverlauf/spieler/34691',
 'https://www.transfermarkt.us/tyrone-mings/marktwertverlauf/spieler/253677',
 'https://www.transfermarkt.us/callum-wilson/marktwertverlauf/spieler/123682',
 'https://www.transfermarkt.us/harry-wilson/profil/spieler/279455',
 'https://www.transfermarkt.us/josh-sims/marktwertverlauf/spieler/286919',
 'https://www.transfermarkt.us/daniel-amartey/profil/spieler/214056',
 'https://www.transfermarkt.us/joe-hart/marktwertverlauf/spieler/40204',
 'https://www.transfermarkt.us/sergio-romero/marktwertverlauf/spieler/30690',
 'https://www.transfermarkt.us/david-de-gea/profil/spieler/59377',
 'https://www.transfermarkt.us/morgan-schneiderlin/marktwertverlauf/spieler/56818',
 'https://www.transfermarkt.us/george-boyd/marktwertverlauf/spieler/45623',
 'https://www.transfermarkt.us/daniel-ayala/profil/spieler/78966',
 'https://www.transfermarkt.us/marcus-browne/marktwertverlauf/spieler/391470',
 'https://www.transfermarkt.us/marcos-alonso/profil/spieler/112515',
 'https://www.transfermarkt.us/stewart-downing/profil/spieler/4063',
 'https://www.transfermarkt.us/joshua-king/profil/spieler/91059',
 'https://www.transfermarkt.us/rouwen-hennings/marktwertverlauf/spieler/16311',
 'https://www.transfermarkt.us/lewis-cook/profil/spieler/249089',
 'https://www.transfermarkt.us/matteo-darmian/marktwertverlauf/spieler/54906',
 'https://www.transfermarkt.us/pablo-zabaleta/marktwertverlauf/spieler/20007',
 'https://www.transfermarkt.us/mark-noble/profil/spieler/31835',
 'https://www.transfermarkt.us/daniel-james/profil/spieler/319301',
 'https://www.transfermarkt.us/sam-field/marktwertverlauf/spieler/387331',
 'https://www.transfermarkt.us/shaun-maloney/marktwertverlauf/spieler/9508',
 'https://www.transfermarkt.us/harry-kane/marktwertverlauf/spieler/132098',
 'https://www.transfermarkt.us/mario-pasalic/marktwertverlauf/spieler/205938',
 'https://www.transfermarkt.us/wayne-routledge/marktwertverlauf/spieler/14066',
 'https://www.transfermarkt.us/simon-mignolet/profil/spieler/50219',
 'https://www.transfermarkt.us/scott-mctominay/profil/spieler/315969',

In [13]:
player_1 = tm.scrape_player(player_links[0])
player_1

,Name,ID,Value,Value last updated,DOB,Age,Height (m),Nationality,Citizenship,Position,Other positions,Team,Last club,Since,Joined,Contract expiration,Market value history,Transfer history
0,Jonathan Calleri,284727,€1.50m,"May 26, 2026","Sep 23, 1993",32,1.8,Argentina,[],Centre-Forward,None,São Paulo,None,None,"Jul 25, 2022","Dec 31, 2028",None,"Empty DataFrame Columns: [Season, Date, Left, ..."

In [8]:
nick_pope_link = next(link for link in player_links if "nick-pope" in link)
nick_pope_link

'https://www.transfermarkt.us/nick-pope/profil/spieler/192080'

In [9]:
nick_pope = tm.scrape_player(nick_pope_link)
nick_pope

,Name,ID,Value,Value last updated,DOB,Age,Height (m),Nationality,Citizenship,Position,Other positions,Team,Last club,Since,Joined,Contract expiration,Market value history,Transfer history
0,Nick Pope,192080,€5.00m,"Jun 3, 2026","Apr 19, 1992",34,1.98,England,[England],Goalkeeper,None,Newcastle,None,None,"Jul 1, 2022","Jun 30, 2027",None,"Empty DataFrame Columns: [Season, Date, Left, ..."

In [10]:
minutes_errors_sql = (PROJECT_ROOT / "queries" / "minutes_errors.sql").read_text()
minutes_errors = connection.sql(minutes_errors_sql).pl()

In [11]:
minutes_errors.filter(
    (pl.col("season") == "2026-27") &
    (pl.col("player_team") == "Newcastle") & 
    (pl.col("position") == "GK")
)

shape: (4, 39)
┌─────────────┬─────────┬─────┬─────────────┬───┬────────────┬───────────┬────────────┬────────────┐
│ run_id      ┆ season  ┆ gw  ┆ kickoff_tim ┆ … ┆ seasons_si ┆ age_years ┆ is_pl_newc ┆ is_promote │
│ ---         ┆ ---     ┆ --- ┆ e           ┆   ┆ nce_last_p ┆ ---       ┆ omer       ┆ d_club     │
│ str         ┆ str     ┆ i64 ┆ ---         ┆   ┆ l          ┆ f64       ┆ ---        ┆ ---        │
│             ┆         ┆     ┆ datetime[μs ┆   ┆ ---        ┆           ┆ f64        ┆ f64        │
│             ┆         ┆     ┆ ]           ┆   ┆ f64        ┆           ┆            ┆            │
╞═════════════╪═════════╪═════╪═════════════╪═══╪════════════╪═══════════╪════════════╪════════════╡
│ da88ecc33f2 ┆ 2026-27 ┆ 1   ┆ 2026-08-23  ┆ … ┆ null       ┆ 24.052019 ┆ 1.0        ┆ 0.0        │
│ 141ceb9ec40 ┆         ┆     ┆ 15:30:00    ┆   ┆            ┆           ┆            ┆            │
│ 88bb2aee…   ┆         ┆     ┆             ┆   ┆            ┆           ┆            ┆            │
│ da88ecc33f2 ┆ 2026-27 ┆ 1   ┆ 2026-08-23  ┆ … ┆ 0.0        ┆ 34.283368 ┆ 0.0        ┆ 0.0        │
│ 141ceb9ec40 ┆         ┆     ┆ 15:30:00    ┆   ┆            ┆           ┆            ┆            │
│ 88bb2aee…   ┆         ┆     ┆             ┆   ┆            ┆           ┆            ┆            │
│ da88ecc33f2 ┆ 2026-27 ┆ 1   ┆ 2026-08-23  ┆ … ┆ null       ┆ 20.588638 ┆ 1.0        ┆ 0.0        │
│ 141ceb9ec40 ┆         ┆     ┆ 15:30:00    ┆   ┆            ┆           ┆            ┆            │
│ 88bb2aee…   ┆         ┆     ┆             ┆   ┆            ┆           ┆            ┆            │
│ da88ecc33f2 ┆ 2026-27 ┆ 1   ┆ 2026-08-23  ┆ … ┆ 0.0        ┆ 34.346338 ┆ 0.0        ┆ 0.0        │
│ 141ceb9ec40 ┆         ┆     ┆ 15:30:00    ┆   ┆            ┆           ┆            ┆            │
│ 88bb2aee…   ┆         ┆     ┆             ┆   ┆            ┆           ┆            ┆            │
└─────────────┴─────────┴─────┴─────────────┴───┴────────────┴───────────┴────────────┴────────────┘

In [14]:
connection.close()

In [17]:
output_filepath = PROJECT_ROOT / "data" / "player_links.txt"

with open(output_filepath, "w", encoding="utf-8") as f:
    f.write("\n".join(player_links) + "\n")